### ISSUE TITLE
A twist on taxes

### ISSUE THREAD

**Issue by MrEditUrProject** [toxidroma/alchemy-requests#15]
Make it so the government collects items instead of cash
The Sanitars would bring the taxed item to a chute where the item would be converted into cash and a cut of the items value is given to both komm and the sanitar that brought in the item
It would make police raids on domiciles more incentivized and it would shake up the whole "hehe sit in office with 40% taxes"

**Comment by amanitasolanaceae** [comment]
this isn't how taxes work at all + this seems a lot like it was based on nightmare 3, an entire other game
